name: Deploy To Render

on:
  push:
    branches: [main]  # Trigger deploy on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger deploy on pull request targeting 'main' branch

jobs:
  ci:
    name: Deploy To Render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        if: github.ref == 'refs/heads/actions'  # Make sure the deployment only happens on ''
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          echo "Deploy URL: $deploy_url"  # Debugging step to ensure URL is being set
          curl "$deploy_url"
