name: Deploy To Render

on:
  push:
    branches: [actions]  
  pull_request:
    branches:
      - actions  

jobs:
  ci:
    name: Deploy To Render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        # Only run this step if the branch is 'actions'
        if: github.ref == 'refs/heads/actions'  
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          echo "Deploy URL: $deploy_url"  # Debugging step to ensure URL is being set
          curl "$deploy_url"  # Run curl with the deploy URL
